CameraX 연동
middlefg/Bowlini pull request #3
Opened 2019-10-31 14:16 UTC by BeokBeok

OCR 기능 구현을 위하여 CameraX 연동하였습니다.

구조는 아래와 같습니다.
- app
  - 앱 시작점
- common
  - Base 와 Wrapper
- navigation
  - 네비게이션 컴포넌트 라이브러리 관련
- ocr
  - 카메라 인식 관련 기능
- opencv
  - 추후 ocr 기능을 구현하기 위한 라이브러리

2019-11-01 03:21 UTC, dev-newbie-randy approved these changes
values-night 폴더도 추가되는 것이 좋을 거 같습니다.^^

2019-11-01 10:13 UTC, 2giwon requested changes
한 수 배우고 갑니다

2019-11-01 10:13 UTC, 2giwon commented on ocr/src/main/java/com/beok/bowlini/ocr/OcrFragment.kt
> +                override fun onPermissionDenied(deniedPermissions: MutableList<String>?) {
override fun onPermissionDenied(deniedPermissions: MutableList<String>?) = Unit 이렇게 하면 더 간결해져요

2019-11-01 10:13 UTC, 2giwon commented on ocr/src/main/java/com/beok/bowlini/ocr/OcrFragment.kt
> +            setTargetResolution(Size(640, 480))
사이즈는 의도하신건가요?

2019-11-04 13:34 UTC, BeokBeok commented on ocr/src/main/java/com/beok/bowlini/ocr/OcrFragment.kt
> +            setTargetResolution(Size(640, 480))
72e1f0fefe7d9e86df4554a5f8ab4471d8079220

사이즈는 가이드 문서에 적혀있는 그대로 적었습니다.
하지만, 전체 화면을 전부 카메라가 보여지기 때문에
width 와 height 둘 다 0 으로 변경했습니다.

2019-11-04 13:34 UTC, BeokBeok commented on ocr/src/main/java/com/beok/bowlini/ocr/OcrFragment.kt
> +                override fun onPermissionDenied(deniedPermissions: MutableList<String>?) {
c944490359d800234e64062767e0495f960cc0ad

적용하였습니다.

2019-11-04 13:34 UTC, BeokBeok commented
> values-night 폴더도 추가되는 것이 좋을 거 같습니다.^^

84f5f57e660f2c82b7f5e3ee02f7f0af4fed2df2

폴더 추가했습니다!

2019-11-05 07:48 UTC, 2giwon commented on ocr/src/main/java/com/beok/bowlini/ocr/OcrFragment.kt
> +            setTargetResolution(Size(640, 480))
귯 👍

2019-11-05 07:51 UTC, 2giwon commented on ocr/src/main/java/com/beok/bowlini/ocr/OcrFragment.kt
> +                override fun onPermissionDenied(deniedPermissions: MutableList<String>?) {
LGTM 👍 👎

2019-11-05 07:52 UTC, 2giwon approved these changes
LGTM 👍 💯

2019-11-05 07:54 UTC, merged